---
- name: Install LVM Storage and Configure LVMCluster
  hosts: localhost
  gather_facts: false
  become_method: sudo
  become: true


  vars:
    extra_disks: "{{ extra_disks | default(0) | int }}"
    lvmcluster_template: "templates/d2-storage-lvmcluster.yaml.j2"
    lvmcluster_file: "{{ clusters_dir }}/{{ clustername }}/d2-storage-lvmcluster.yaml"
    kubeconfig_path: "{{ clusters_dir }}/{{ clustername }}/auth/kubeconfig"  # Caminho do kubeconfig

  tasks:
    - name: Ensure openshift-storage namespace exists
      ansible.builtin.k8s:
        state: present
        api_version: v1
        kind: Namespace
        name: openshift-storage
      environment:  # Passando o kubeconfig pelo ambiente
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Ensure OperatorGroup exists in openshift-storage namespace
      ansible.builtin.k8s:
        state: present
        api_version: operators.coreos.com/v1
        kind: OperatorGroup
        name: openshift-storage-operatorgroup
        namespace: openshift-storage
        definition:
          metadata:
            name: openshift-storage-operatorgroup
            namespace: openshift-storage
          spec:
            targetNamespaces:
              - openshift-storage
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Ensure LVMS Subscription exists
      ansible.builtin.k8s:
        state: present
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        name: lvms
        namespace: openshift-storage
        definition:
          spec:
            installPlanApproval: Automatic
            name: lvms-operator
            source: redhat-operators
            sourceNamespace: openshift-marketplace
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Wait for LVM Storage operator to be installed
      ansible.builtin.k8s_info:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        namespace: openshift-storage
      register: lvm_csv_check
      retries: 10
      delay: 30
      until: "'Succeeded' in lvm_csv_check.resources[0].status.phase"
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Display LVM Storage installation status
      debug:
        var: lvm_csv_check.resources[0].status.phase

    - name: Generate the list of extra disks
      set_fact:
        extra_disks_list: "{{ ['vdb', 'vdc', 'vdd', 'vde', 'vdf', 'vdg', 'vdh', 'vdi', 'vdj', 'vdk'][:extra_disks] }}"

    - name: Display the generated list of extra disks
      debug:
        var: extra_disks_list

    - name: Render the LVMCluster template with extra disks
      ansible.builtin.template:
        src: "{{ lvmcluster_template }}"
        dest: "{{ lvmcluster_file }}"

    - name: Apply the LVMCluster resource
      ansible.builtin.k8s:
        state: present
        src: "{{ lvmcluster_file }}"
        namespace: openshift-storage
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Wait for LVMCluster to be in Ready status
      ansible.builtin.k8s_info:
        api_version: lvm.topolvm.io/v1alpha1
        kind: LVMCluster
        namespace: openshift-storage
      register: lvmcluster_status
      retries: 10
      delay: 30
      until: lvmcluster_status.resources | length > 0 and lvmcluster_status.resources[0].status.state == 'Ready'
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Ensure PVC exists in default namespace
      ansible.builtin.k8s:
        state: present
        api_version: v1
        kind: PersistentVolumeClaim
        name: example-pvc-rwo
        namespace: default
        definition:
          spec:
            accessModes:
              - ReadWriteOnce
            resources:
              requests:
                storage: 5Gi
            storageClassName: lvms-vg1
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Ensure Pod exists in default namespace
      ansible.builtin.k8s:
        state: present
        api_version: v1
        kind: Pod
        name: busybox
        namespace: default
        definition:
          spec:
            containers:
              - name: busybox
                image: busybox
                command: [ "/bin/sh", "-c", "while true ; do date; sleep 1; done;" ]
                volumeMounts:
                  - mountPath: /pvc
                    name: pvc
            volumes:
              - name: pvc
                persistentVolumeClaim:
                  claimName: example-pvc-rwo
            restartPolicy: Never
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Display Pod creation status
      ansible.builtin.k8s_info:
        api_version: v1
        kind: Pod
        namespace: default
      register: pod_info
      environment:
        KUBECONFIG: "{{ kubeconfig_path }}"

    - name: Display Pod details
      debug:
        var: pod_info.resources